<?php
	$_sliderConfig	= Mage::getStoreConfig('logo/logo/display');
	if($_sliderConfig==1)
	{
		
	
	$_animateSpeed	= Mage::getStoreConfig('logo/logo/speed');
	if($_animateSpeed==' ')
		$_animateSpeed = 4000;

	$_totalDisplay	= Mage::getStoreConfig('logo/logo/numbers');
	if($_totalDisplay==' ')
		$_totalDisplay = 8;

	$_displayType	= Mage::getStoreConfig('logo/logo/setype');
	$cur_date    	= date("Y-m-d");
?>
<script src="<?php echo $this->getSkinUrl('js/jquery-1.9.1.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery.jcarousel.min.js');?>" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/skin.css') ?>"/>
<style type="text/css">
.jcarousel-skin-tango .jcarousel-container-horizontal {
    width: 92%;
}
.jcarousel-skin-tango .jcarousel-clip-horizontal {
    width: 100%;
}
</style>
<script type="text/javascript">
function mycarousel_initCallback(carousel)
{
    // Disable autoscrolling if the user clicks the prev or next button.
    carousel.buttonNext.bind('click', function() {
        carousel.startAuto(0);
    });

    carousel.buttonPrev.bind('click', function() {
        carousel.startAuto(0);
    });

    // Pause autoscrolling if the user moves with the cursor over the clip.
    carousel.clip.hover(function() {
        carousel.stopAuto();
    }, function() {
        carousel.startAuto();
    });
};

jQuery(document).ready(function() {
    jQuery('#mycarousel').jcarousel({
        visible: 4,
	auto : 2,
	wrap: 'circular',
	animation: <?php echo $_animateSpeed;?>,
	initCallback: mycarousel_initCallback
    });
});
</script>
<div id="wrap">
<?php
	if($_displayType==1)
	{
		
		$collection = Mage::getModel('slider/slider')->categorySlider();
?>
		<ul id="mycarousel" class="jcarousel-skin-tango">
<?php
		foreach ($collection as $_cat)
		{
			$_brandCatId	= $_cat->getEntityId();
			$_loadbrandCat	= Mage::getModel('catalog/category')->load($_brandCatId);
			$_brandImageSrc	= $_loadbrandCat->getImageUrl();
			$_brandLink	= $_loadbrandCat->getLogoLink();
			$_catUrl	= $_loadbrandCat->getUrl();
			if($_brandLink==' ')
				$_brandLink = $_catUrl;
?>
			<li><a href="<?php echo $_brandLink;?>"><img src="<?php echo $_brandImageSrc;?>" width="188" height="90" alt="" /></a></li>
<?php
		}
?>
		</ul>
<?php
	}
	else if($_displayType==2)
	{
		
		$prodCollection = $collection = Mage::getModel('slider/slider')->productSlider();
?>
		<ul id="mycarousel" class="jcarousel-skin-tango">
<?php
		foreach ($prodCollection as $_cat)
		{
			$_brandCatId	= $_cat->getEntityId();
			$_loadbrandCat	= Mage::getModel('catalog/product')->load($_brandCatId);
			$_brandImageSrc	= $_loadbrandCat->getImageUrl();
			$_brandLink	= $_loadbrandCat->getLogoLink();
			$_catUrl	= $_loadbrandCat->getProductUrl();
			if($_brandLink==' ')
				$_brandLink = $_catUrl;
?>
			<li><a href="<?php echo $_brandLink;?>"><img src="<?php echo $_brandImageSrc;?>" width="188" height="90" alt="" /></a></li>
<?php
		}
?>
		</ul>
<?php
	}

?>
</div>
<?php } ?>